[package]
name = "nannou-gallery"
version = "0.0.1"
authors = ["Fjutil Artworks"]
edition = "2021"

[features]
input-msmf = ["nokhwa/input-msmf"]

[dependencies]
nokhwa = "0.8.0"
nannou="0.17.1"
rand="0.8.1"
unique_id="0.1.3"
lazy_static = "1.4.0"